contact_links:
  - name: Предложение
    url: https://discord.gg/CuWu6kSznf #A-13
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.gg/CuWu6kSznf #A-13
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности lemird (634710558364663819) или 13lackhawk (236910741146304515) в Discord.
