- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Omega
  - Bagel
#  - Barratry
  - Box
  - CorvaxAstra
#  - CorvaxSpectrum
  - Cluster
  - Packed
#  - CorvaxAvrite
  - Marathon
  - CorvaxOutpost
  - Meta
#  - CorvaxDelta
  - Fland
  - Core
#  - Origin
  - CorvaxSilly
  - Atlas
  - Saltern
#  - Reach
#  - Train <- return after station anchoring PR is finished and merged
